---

- name: install conky
  become: yes
  package:
    name: "{{ item }}"
  with_items:
    - "conky"
    - "ttf-dejavu"


- name: ensure conky config dir exists
  file:
    path: "~/.config/conky"
    state: "directory"

- name: config conky
  copy:
    src: "files/conky.conf.lua"
    dest: "~/.config/conky/conky.conf"

...
