---
- name: install base development packages and helpers
  become: yes
  package:
    name: "{{ item }}"
  with_items:
    - "base-devel"
    - "fd"
    - "ripgrep"
    - "entr"

- name: pull pikaur
  git:
    repo: https://aur.archlinux.org/pikaur.git
    dest: ~/lib/pikaur

- name: make and install pikaur
  command: makepkg -fsri --noconfirm
  args:
    chdir: /home/jtmoulia/lib/pikaur
