---
- name: install base development packages
  become: yes
  package:
    name: base-devel

- name: pull pikaur
  git:
    repo: https://aur.archlinux.org/pikaur.git
    dest: ~/lib/pikaur

- name: make and install pikaur
  command: makepkg -fsri --noconfirm
  args:
    chdir: /home/jtmoulia/lib/pikaur

- name: install wpa_actiond
  become: yes
  package:
    name: wpa_actiond
  tags: [network]

- name: enable network interface
  become: yes
  systemd:
    name: "netctl-auto@{{ wifi_interface }}.service"
    enabled: true
    state: "started"
  tags: [network]
