---

- name: install GUI apps
  become: yes
  package:
    name: "{{ item }}"
  with_items:
    - firefox
    - chromium
    - termite
    - vlc

- name: install GUI apps from aur
  command: "pikaur -Sy --noconfirm --noprogressbar {{ item }}"
  with_items:
    - spotify
    - slack-desktop
