[project]
name = "dotfiles"
version = "0.1.0"
description = "jtmoulia's dotfiles"
readme = "README.md"
requires-python = ">=3.13"
license = "BSD-3-Clause"
dependencies = [
    "ansible",
    "jinja2",
    "PyYAML",
]
