---


- name: restart firewalld
  become: yes
  service:
    name: firewalld
    state: restarted
  notify:
    "restart libvirtd"

- name: restart libvirtd
  become: yes
  service:
    name: libvirtd
    state: restarted

...
