---
- name: install some net packages
  become: yes
  package:
    name: "{{ item }}"
    state: lastest
  with_items:
    - openssl
    - nmap

- name: copy in scripts
  copy:
    src: "files/{{ item }}"
    dest: "~/bin/{{ item }}"
  with_items:
    - ssl-info
