---
- name: install offlineimap
  become: yes
  package:
    name: offlineimap
    state: latest

- name: copy in .offlineimaprc
  copy:
    src: "files/offlineimaprc"
    dest: "~/.offlineimaprc"

- name: copy in .offlineimap.py
  copy:
    src: "files/offlineimap.py"
    dest: "~/.offlineimap.py"

- name: copy in sdcript to kill offlineimap
  copy:
    src: "files/kill-offlineimap.sh"
    dest: "~/bin/kill-offlineimap"
