---
- name: install offlineimap
  become: yes
  package:
    state: "latest"
    name: "offlineimap"

- name: symlink in .offlineimaprc
  file:
    state: "link"
    src: "{{ role_path }}/files/offlineimaprc"
    dest: "~/.offlineimaprc"

- name: symlink in .offlineimap.py
  file:
    state: "link"
    src: "{{ role_path }}/files/offlineimap.py"
    dest: "~/.offlineimap.py"

- name: symlink in pass-get script
  file:
    state: "link"
    src: "{{ role_path }}/files/pass-get.bash"
    dest: "~/.local/bin/pass-get"

- name: symlink in script to kill offlineimap
  file:
    state: "link"
    src: "{{ role_path }}/files/kill-offlineimap.sh"
    dest: "~/.local/bin/kill-offlineimap"
    mode: 0770

- name: symlink in script to run offlineimap
  file:
    state: "link"
    src: "{{ role_path }}/files/my-offlineimap.sh"
    dest: "~/.local/bin/my-offlineimap"
    mode: 0770
