---

- name: ensure tmux is installed
  become: yes
  package:
    name: tmux

- name: symlink in tmux.conf
  file:
    state: "link"
    src: "{{ role_path }}/files/tmux.conf"
    dest: "~/.tmux.conf"

- name: install tmuxinator from AUR
  become: yes
  command: pikaur -Sy --noconfirm --noprogressbar tmuxinator

- name: install tmuxinator configs
  copy:
    src: "files/tmuxinator/"
    dest: "~/.config/tmuxinator"
