---

- name: ensure tmux is installed
  become: yes
  package:
    name: tmux

- name: symlink in tmux.conf
  file:
    state: "link"
    src: "{{ role_path }}/files/tmux.conf"
    dest: "~/.tmux.conf"
