---

- name: ensure tmux is installed
  become: "{{ privileged_package_install }}"
  package:
    name: tmux

- name: symlink in tmux.conf
  file:
    state: "link"
    src: "{{ role_path }}/files/tmux.conf"
    dest: "~/.tmux.conf"
