---
- name: install/update pass
  become: "{{ privileged_package_install }}"
  package:
    state: "latest"
    name: "pass"

- name: clone password store
  git:
    repo: "jtmoulia@shed.pocketknife.io:/home/jtmoulia/repos/password-store.git"
    dest: "~/.password-store"

# TODO: move this under a GPG specific role
- name: ensure gpg-agent config exists
  when: hostvars.localhost.ansible_os_family != "Darwin"
  file:
    state: "directory"
    dest: "~/.gnugpg"

- name: symlink in gpg-agent config
  when: hostvars.localhost.ansible_os_family != "Darwin"
  file:
    state: "link"
    src: "{{ role_path }}/files/gpg-agent.conf"
    dest: "~/.gnugpg/gpg-agent.conf"
