#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Share history across sessios
SHARE_HISTORY=t
TERM=screen-256color
# Assumes neovim is installed
EDITOR=nvim
PAGER=less

# Aliases

# Use exa over ls if it's installed
if $(which exa &>/dev/null); then
  alias l='exa --oneline'
  alias ls='exa'
  alias ll='exa --long --all'
fi

# Define helper wrapping xclip or wl-copy
# Usage: `echo "copy this" | xc``
if $(which xclip &>/dev/null); then
   alias xc='xclip -selection c'
fi

if $(which wl-copy &>/dev/null); then
   alias xc='wl-copy'
fi

if $(which keychain &>/dev/null); then
  eval $(keychain --eval --agents ssh,gpg id_rsa)
fi

# General fzf config and install

if [ -f ~/.fzf.zsh ]; then
  FZF_TMUX_OPTS="-d 40%"
  alias f='fzf --preview "bat --color \"always\" {}"'
  source ~/.fzf.zsh
fi

# Update path
PATH="$HOME/.local/bin:$PATH"

