# -*- mode: sh -*-
#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Thomas Moulia <jtmoulia@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Share history across sessios
SHARE_HISTORY=t
TERM=screen-256color
PAGER=less

# MacOS Homebrew specific completions
if type brew &>/dev/null; then
  FPATH=$(brew --prefix)/share/zsh-completions:$FPATH

  autoload -Uz compinit
  compinit
fi

# Aliases
if $(which xdg-open &>/dev/null); then
  alias o='xdg-open'
fi

if $(which curl &>/dev/null); then
  alias wttr="curl 'wttr.in/~Morgan+Hill?u'"
  alias wttr2="curl 'v2.wttr.in/~Morgan+Hill?u'"
fi

# Tailscale alias if it's installed as an OS X app
if [ -f /Applications/Tailcale.app/Contents/MacOS/Tailscale ]; then
  alias tailscale='/Applications/Tailcale.app/Contents/MacOS/Tailscale'
fi

# Alias mkpass as an xkcdpass heper if installed
if $(which xkcdpass &>/dev/null); then
  alias mkpass='xkcdpass --max 16 --case random --random-delimiters --numwords 3'
fi

# Use nvim if it's installed
if $(which nvim &>/dev/null); then
  EDITOR=nvim
  alias vi=nvim
else
  # Fallback to vi, typically aliased to vim
  if $(which vi &>/dev/null); then
     EDITOR=vi
  fi

fi

# Use exa over ls if it's installed
if $(which exa &>/dev/null); then
  alias l='exa --oneline --icons'
  alias ls='exa --icons'
  alias ll='exa --long --all --icons'
fi

# Define helper wrapping xclip or wl-copy
# Usage: `echo "copy this" | xc``
if $(which xclip &>/dev/null); then
   alias xc='xclip -selection c'
fi

if $(which wl-copy &>/dev/null); then
   alias xc='wl-copy'
else
  # OS X pbcopy
  if $(which pbcopy &>/dev/null); then
    alias xc='pbcopy'
  fi
fi

if $(which keychain &>/dev/null); then
  eval $(keychain --eval --ssh-spawn-gpg)
fi

# General fzf config and install

fzf_keybindings_file=
if [ -f /usr/share/fzf/key-bindings.zsh ]; then
  fzf_keybindings_file=/usr/share/fzf/key-bindings.zsh
elif [ -f ~/.zsh ]; then
  fzf_keybindings_file=~/.zsh
else
  fzf_keybindings_file="$(find /opt/homebrew/Cellar/fzf -name key-bindings.zsh)"
fi

if [ "$fzf_keybindings_file" ]; then
  source "$fzf_keybindings_file"
fi

if $(which fzf &>/dev/null); then
  FZF_TMUX_OPTS="-d 40%"
  alias f='fzf --preview "bat --color \"always\" {}"'
fi

if $(which zoxide &>/dev/null); then
  eval "$(zoxide init zsh)"
fi

# Update path
PATH="$HOME/.local/bin:$PATH"

# Setup guix
GUIX_PROFILE="/home/jtmoulia/.guix-profile"
if [ -d "$GUIX_PROFILE" ]; then
  . "$GUIX_PROFILE/etc/profile"
fi

# Setup NPM path for installing global packages to local user path
export npm_config_prefix="$HOME/.local"
