---
- name: install python and some niceties
  become: yes
  package:
    name: "{{ item }}"
    state: latest
  with_items:
    - python
    - python-pip
    - ipython
    - jupyter
    # flake8: python linting
    - flake8
    # jedi: python refactoring and autocompletion
    - python-jedi
    # pipenv: a marriage between virtualenv and pip
    - python-pipenv
    # black: python code formatter
    - python-black
    # pdb++: a sweet drop-in replacement for pdb
    # - pdbpp (currently in aur)

- name: clone mkpass
  git:
    repo: "jtmoulia@shed.pocketknife.io:~/repos/mkpass.git"
    dest: "~/repos/mkpass"

- name: install mkpass
  become: yes
  pip:
    name: "file:///home/jtmoulia/repos/mkpass"
    editable: yes
