---
- name: install python and some niceties
  become: yes
  package:
    name: "{{ item }}"
    state: latest
  with_items:
    - python
    - python-pip
    - ipython
    - jupyter
    - flake8
    - python-jedi
    - python-pipenv
