---

- name: install git
  become: true
  package:
    name: git
    state: latest

- name: configure git
  git_config:
    name: "{{ item.name }}"
    scope: global
    value: "{{ item.value }}"
  with_items:
    - {name: "user.name", value: "Thomas Moulia"}
    - {name: "user.email", value: "jtmoulia@gmail.com"}
