---

- name: install git
  become: true
  package:
    name: git
    state: latest

- name: symlink in global gitconfig
  file:
    state: "link"
    src: "{{ role_path }}/files/gitconfig"
    dest: "~/.gitconfig"
