#!/usr/bin/env bash
for key in ~/.ssh/{id_rsa,id_rsa_gitlab,healthtensor,hippo,research-bastion.pem,cesium-test.pem}; do
    if [ -e "$key" ]; then
        ssh-add "$key"
    fi
done

pass-show() {
    pass show "$1" | head -n1
}

# echo "$(pass-show ssh-id_rsa)"
# ssh-add-pass ~/.ssh/id_rsa "$(pass-show ssh-id_rsa)"
# ssh-add-pass ~/.ssh/id_rsa_gitlab "$(pass-show ssh-gitlab)"
