#!/bin/sh

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# Set HiDPI defaults
export QT_SCALE_FACTOR={{ xinitrc_qt_scale_factor }}
export GDK_SCALE={{ xinitrc_gdk_scale }}

# merge in defaults and keymaps

if [ -f $sysresources ]; then
    xrdb -merge $sysresources
fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then
    xrdb -merge "$userresources"
fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

# start some nice programs

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

if [[ "$(which sleepd)" ]]; then
  sleepd
fi

if [[ "$(which xscreensaver)" ]]; then
    xscreensaver -no-splash &
fi

if [ "$(which tint2)" ]; then
    tint2 &
fi

if [[ -f ~/.fehbg ]]; then
    ~/.fehbg &
fi

DIRCOLORS_THEME=/home/jtmoulia/repos/dircolors-solarized/dircolors.ansi-dark
if [[ -b "$DIRCOLORS_THEME" ]]; then
    eval $(dircolors "$DIRCOLORS_THEME")
fi

# Turn off the hated (if sometimes useful) beep
xset -b

# Replace the valuable caps real-estate with the ctrl key
setxkbmap -option caps:ctrl_modifier

# replace this process with stumpwm!
exec stumpwm
