#!/usr/bin/env bash
server="$1"
if [ ! "$server" ]; then
    >&2 echo "Error: missing SERVER argument!"
    >&2 echo "Usage: ssl-info SERVER"
    exit 1
fi

echo \
    | openssl s_client -servername "${server}" -connect "${server}":443 2>/dev/null \
    | openssl x509 -noout -issuer -subject -dates
