---

- name: ensure nyxt is installed
  become: yes
  package:
    # note this will likely fail as it's an AUR package
    name: nyxt

- name: symlink in nyxt config files
  file:
    state: "link"
    src: "{{ role_path }}/files/{{ item }}"
    dest: "~/.config/nyxt/{{ item }}"
  with_items:
    # TODO: symlink in all files in one pass?
    - "auto-config.lisp"
    - "init.lisp"
    - "my-slynk.lisp"
