---
- name: install/update core libraries
  become: true
  package:
    name: "{{ item }}"
    state: latest
  with_items:
    - neovim
    - ansible
    - fish
    - sudo
    - openssh
    - fzf
    - fd
    - ripgrep
    - tldr

- name: add jtmoulia
  become: true
  user:
    name: jtmoulia
    shell: /usr/bin/fish
    groups: wheel
    generate_ssh_key: yes
    ssh_key_bits: 4096
