---
- name: install/update core libraries
  become: "{{ privileged_package_install }}"
  package:
    name: "{{ item }}"
    state: latest
  with_items:
    - neovim
    - tldr
    - perl
    # A CLI interface that respects the trash can
    - trash-cli
    # Gotta be able to [un]zip
    - unzip
    # A more modern [and fun] grep
    - ripgrep
    # An SSH agent wrapper for the shell
    - keychain

- name: install/update non OS X libraries
  become: "{{ privileged_package_install }}"
  when: hostvars.localhost.ansible_os_family != "Darwin"
  package:
    name: "{{ item }}"
    state: latest
  with_items:
    - sudo

- name: add default user
  become: true
  # Do not set up the default user if configured on OS X
  when: hostvars.localhost.ansible_os_family != "Darwin"
  user:
    name: "{{ default_user }}"
    groups: "{{ sudo_group }}"
    generate_ssh_key: yes
    ssh_key_bits: 4096

- name: ensure the user bin directory exists
  file:
    path: "~/.local/bin"
    state: directory
