---
- name: install/update core libraries
  become: true
  package:
    name: "{{ item }}"
    state: latest
  with_items:
    - neovim
    - ansible
    - sudo
    - fd
    - ripgrep
    - tldr
    - perl
    # A CLI interface that respects the trash can
    - trash-cli
    - unzip

- name: add jtmoulia
  become: true
  user:
    name: jtmoulia
    groups: wheel
    generate_ssh_key: yes
    ssh_key_bits: 4096
