---
- name: install/update core libraries
  become: true
  package:
    name: "{{ item }}"
    state: latest
  with_items:
    - neovim
    - ansible
    - sudo
    - tldr
    - perl
    # A CLI interface that respects the trash can
    - trash-cli
    - unzip

- name: add jtmoulia
  become: true
  user:
    name: jtmoulia
    groups: "{{ sudo_group }}"
    generate_ssh_key: yes
    ssh_key_bits: 4096

- name: ensure the user bin directory exists
  file:
    path: "~/bin"
    state: directory
