---

- name: install xorg packages (arch)
  become: yes
  package:
    name: "{{ item }}"
  with_items:
    - xorg-server
    - xorg-xinit
    - feh
    # - xorg-xmodmap

- name: template in .xinitrc file
  template:
    src: "templates/xinitrc"
    dest: "~/.xinitrc"

# - name: copy in .Xmodmap file
#   copy:
#     src: "files/Xmodmap"
#     dest: "~/.Xmodmap"

- name: copy in .Xresources file
  copy:
    src: "files/Xresources"
    dest: "~/.Xresources"

- name: ensure ~/.config/xinitrc.d dir exists
  file:
    path: "~/.config/xinitrc.d"
    state: directory

- name: copy in caps_to_ctrl.sh
  copy:
    src: "files/caps_to_ctrl.sh"
    dest: "~/.config/xinitrc.d/caps_to_ctrl.sh"

- name: copy in ssh-agent.service
  copy:
    src: "files/ssh-agent.service"
    dest: "~/.config/systemd/user/ssh-agent.service"

- name: enable the ssh-agent.service
  systemd:
    name: ssh-agent
    scope: user
    enabled: true
    state: started
