---

- name: install xorg packages (arch)
  become: yes
  package:
    name: "{{ item }}"
  with_items:
    - xorg-server
    - xorg-xinit
    - feh
    - xterm
    # - xorg-xmodmap

- name: template in .xinitrc file
  template:
    src: "templates/xinitrc"
    dest: "~/.xinitrc"

# - name: copy in .Xmodmap file
#   copy:
#     src: "files/Xmodmap"
#     dest: "~/.Xmodmap"

- name: copy in .Xresources file
  copy:
    src: "files/Xresources"
    dest: "~/.Xresources"

- name: ensure ~/.config/xinitrc.d dir exists
  file:
    path: "~/.config/xinitrc.d"
    state: directory

- name: copy in caps_to_ctrl.sh
  copy:
    src: "files/caps_to_ctrl.sh"
    dest: "~/.config/xinitrc.d/caps_to_ctrl.sh"


- name: copy in the systemd user xsession.target file
  copy:
    src: "files/xsession.target"
    dest: "~/.config/systemd/user"
    mode: 0640

- name: copy in the systemd-start-graphical-session script
  copy:
    src: "files/systemd-start-graphical-session.sh"
    dest: "~/bin/systemd-start-graphical-session"
    mode: 0750

- name: copy in monitor config script
  copy:
    src: files/configure-monitors.elv
    dest: ~/.local/bin/configure-monitors
    mode: 0755

- name: copy in udev hotplug rules
  become: yes
  copy:
    src: files/98-monitor-hotplug.rules
    dest: /etc/udev/rules.d/98-monitor-hotplug.rules
    mode: 0644
