---
- name: install pulseaudio and utilities
  become: yes
  package:
    name: "{{ item }}"
    state: latest
  with_items:
    - pulseaudio
    - pulseaudio-alsa
    - pulseaudio-bluetooth
    - pulsemixer
    - pavucontrol
