---
- name: install bash & others
  become: yes
  package:
    name: "{{ item }}"
    state: "latest"
  with_items:
    - "bash"
    - "fzf"

- name: symlink in .bashrc
  file:
    state: "link"
    src: "{{ role_path }}/files/bashrc"
    dest: "~/.bashrc"

- name: symlink in .bash_profile
  file:
    state: "link"
    src: "{{ role_path }}/files/bash_profile"
    dest: "~/.bash_profile"

- name: git clone bash-it
  git:
    repo: "git@github.com:Bash-it/bash-it.git"
    dest: "~/.local/lib/bash_it"
    depth: 1
