---
- name: install bash & others
  become: yes
  package:
    name: "{{ item }}"
    state: "latest"
  with_items:
    - "bash"
    - "fzf"

- name: copy in .bashrc
  copy:
    src: "files/bashrc"
    dest: "~/.bashrc"

- name: copy in .bash_profile
  copy:
    src: "files/bash_profile"
    dest: "~/.bash_profile"
