---
- name: install/update emacs
  become: true
  package:
    name: "{{ item }}"
    state: "latest"
  with_items:
    # currently using compiled AUR emacs-native-comp-git
    # - "emacs"
    - "fasd"
    - "aspell-en"

# - name: install mu & mu4e if enabled
#  become: yes
#  package:
#    name: "mu"
#    state: "latest"
#  when: emacs_mu4e_enabled

# config (doom)

- name: install doom (dev branch)
  git:
    repo: "https://github.com/hlissner/doom-emacs"
    dest: "~/.emacs.d"
    version: "develop"

- name: install doom config
  file:
    state: "link"
    src: "{{ role_path }}/files/doom.d/"
    dest: "~/.doom.d"

# WARNING: This command blocks for user-input
# - name: upgrade doom
#   command: "~/.emacs.d/bin/doom upgrade"
#   notify:
#     - "restart emacs"

# systemd (emacs.service)

- name: ensure systemd/user dir exists
  file:
    path: "~/.config/systemd/user"
    state: "directory"

- name: symlink in emacs systemd service
  file:
    state: "link"
    src: "{{ role_path }}/files/emacs.service"
    dest: "~/.config/systemd/user/emacs.service"
  notify:
    - "restart emacs"

- name: enable the emacs service
  systemd:
    name: "emacs"
    scope: "user"
    enabled: true
    state: "started"

- name: symlink in emacsclient.desktop
  become: yes
  file:
    state: "link"
    src: "{{ role_path }}/files/emacsclient.desktop"
    dest: "/usr/share/applications/doomclient.desktop"
    mode: 0755
