---
- name: install/update emacs
  become: true
  package:
    name: "{{ item }}"
    state: latest
  with_items:
    - emacs
    - mu
    - html2text

# config (spacemacs)

- name: install spacemacs (dev branch)
  git:
    repo: https://github.com/syl20bnr/spacemacs
    dest: "~/.emacs.d"
    version: develop

- name: install spacemacs config
  copy:
    src: "files/spacemacs.d/"
    dest: "~/.spacemacs.d"

- name: template in the spacemacs config
  template:
    src: "templates/init.el.j2"
    dest: "~/.spacemacs.d/init.el"

# org-jira

- name: ensure repos exists
  file:
    path: "~/repos"
    state: directory
  tags: ["org-jira"]

- name: clone org-jira
  git:
    repo: "git@github.com:jfim/org-jira.git"
    dest: "~/repos/org-jira"
  tags: ["org-jira"]

- name: link in org-jira as a private spacemacs layer
  file:
    src: "~/repos/org-jira"
    dest: "~/.emacs.d/private/org-jira"
    state: link
  tags: ["org-jira"]

# systemd (emacs.service)

- name: ensure that the emacs systemd directory exists
  file:
    path: "~/.config/systemd/user"
    state: directory

- name: copy in the emacs systemd service
  copy:
    src: "files/emacs.service"
    dest: "~/.config/systemd/user/emacs.service"

- name: enable the emacs service
  systemd:
    name: emacs
    scope: user
    enabled: true
    state: started
