---
- name: install/update emacs
  become: true
  package:
    name: "{{ item }}"
    state: latest
  with_items:
    - "emacs"
    - "fasd"

- name: install mu & mu4e if enabled
  package:
    name: "mu"
    state: "latest"
  when: emacs_mu4e_enabled

# config (spacemacs)

- name: install spacemacs (dev branch)
  git:
    repo: https://github.com/syl20bnr/spacemacs
    dest: "~/.emacs.d"
    version: develop

- name: install spacemacs config
  copy:
    src: "files/spacemacs.d/"
    dest: "~/.spacemacs.d"

- name: template in the spacemacs config
  template:
    src: "templates/init.el.j2"
    dest: "~/.spacemacs.d/init.el"

# org-jira

- name: include org-jira tasks if emacs_org_jira_enabled
  include_tasks:
    file: "tasks/org_jira.yml"
  when: emacs_org_jira_enabled
  tags: ["org-jira"]

# systemd (emacs.service)

- name: ensure that the emacs systemd directory exists
  file:
    path: "~/.config/systemd/user"
    state: directory

- name: copy in the emacs systemd service
  copy:
    src: "files/emacs.service"
    dest: "~/.config/systemd/user/emacs.service"

- name: enable the emacs service
  systemd:
    name: emacs
    scope: user
    enabled: true
    state: started
