---
- name: install/update emacs
  become: "{{ privileged_package_install }}"
  when: privileged_package_install | default(true) | bool
  package:
    name: "{{ item }}"
    state: "latest"
  with_items:
    # Use emacs-wayland for pgtk and native-comp
    - "emacs-wayland"
    - "fasd"
    - "aspell"
    - "ttf-dejavu"

- name: install/update linux specific emacs deps
  become: "{{ privileged_package_install }}"
  when: ansible_facts['os_family'] != "Darwin" and (privileged_package_install | default(true) | bool)
  package:
    name: "{{ item }}"
    state: "latest"
  with_items:
    - "aspell-en"

# config (hogmacs: https://git.sr.ht/~jtmoulia/hogmacs)

- name: clone hogmacs config
  git:
    repo: "git@git.sr.ht:~jtmoulia/hogmacs"
    dest: "~/src/hogmacs"
    version: "trunk"
    update: yes

- name: tangle hogmacs literate config to init.el
  command: emacs --batch --eval "(require 'org)" --eval "(org-babel-tangle-file \"README.org\")"
  args:
    chdir: "~/src/hogmacs"

- name: ensure ~/.config/emacs directory exists
  file:
    state: "directory"
    path: "~/.config/emacs"

- name: symlink in hogmacs init.el
  file:
    state: "link"
    src: "~/src/hogmacs/init.el"
    dest: "~/.config/emacs/init.el"

# systemd (emacs.service)

- name: ensure systemd/user dir exists
  when: ansible_facts['os_family'] != "Darwin"
  file:
    path: "~/.config/systemd/user"
    state: "directory"

- name: symlink in emacs systemd service
  when: ansible_facts['os_family'] != "Darwin"
  file:
    state: "link"
    src: "{{ role_path }}/files/emacs.service"
    dest: "~/.config/systemd/user/emacs.service"
  notify:
    - "restart emacs"

- name: enable the emacs service
  when: ansible_facts['os_family'] != "Darwin"
  systemd:
    name: "emacs"
    scope: "user"
    enabled: true
    state: "started"

- name: symlink in emacsclient.desktop
  when: ansible_facts['os_family'] != "Darwin" and (privileged_package_install | default(true) | bool)
  become: yes
  file:
    state: "link"
    src: "{{ role_path }}/files/emacsclient.desktop"
    dest: "/usr/share/applications/emacsclient.desktop"
    mode: 0755
