---
- name: install/update emacs
  become: true
  package:
    name: "{{ item }}"
    state: latest
  with_items:
    - "emacs-git"
    - "fasd"
    - "aspell-en"

- name: install mu & mu4e if enabled
  package:
    name: "mu"
    state: "latest"
  when: emacs_mu4e_enabled

# config (doom)

- name: install doom (dev branch)
  git:
    repo: https://github.com/hlissner/doom-emacs
    dest: "~/.emacs.d"
    version: develop

- name: install spacemacs config
  copy:
    src: "files/doom.d/"
    dest: "~/.doom.d"

# - name: template in the spacemacs config
#   template:
#     src: "templates/init.el.j2"
#     dest: "~/.spacemacs.d/init.el"
#   notify:
#     - restart emacs

- name: upgrade doom
  command: ~/.emacs.d/bin/doom upgrade
  notify:
    - restart emacs

# systemd (emacs.service)

- name: ensure that the emacs systemd directory exists
  file:
    path: "~/.config/systemd/user"
    state: directory

- name: copy in the emacs systemd service
  copy:
    src: "files/emacs.service"
    dest: "~/.config/systemd/user/emacs.service"
  notify:
    - restart emacs

- name: enable the emacs service
  systemd:
    name: emacs
    scope: user
    enabled: true
    state: started
