---
- name: install automed dependencies
  become: yes
  package:
    name: "{{ item }}"
    state: "latest"
  with_items:
    - "ansible"
    - "python-jinja"
    - "certbot"

- name: install mkcert from aur
  become: yes
  command: "pikaur -Sy --noconfirm --noprogressbar mkcert"

- name: copy in helpful binaries
  copy:
    src: "files/{{ item.src }}"
    dest: "~/.local/bin/{{ item.dest }}"
  with_items:
    - {src: "ssh-add-hippos", dest: "ssh-add-hippos"}
    - {src: "ssh-automed.bash", dest: "ssh-automed"}

- name: ensure the repos directory exists
  file:
    path: "~/repos"
    state: "directory"

- name: clone automed
  git:
    repo: "git@gitlab.com:HealthTensor/automed.git"
    dest: "~/repos/automed"
    update: no

- name: setup symbolic link
  file:
    src: "~/repos/automed/bin/automed-compose.sh"
    dest: "~/bin/ac"
    state: "link"
