---
- name: install automed dependencies
  become: "{{ privileged_package_install }}"
  package:
    name: "{{ item }}"
    state: "latest"
  with_items:
    - "ansible"
    - "certbot"

- name: install mkcert from aur
  when: hostvars.localhost.ansible_os_family != "Darwin"
  become: yes
  command: "pikaur -Sy --noconfirm --noprogressbar mkcert"

- name: install mkcert from homebrew
  when: hostvars.localhost.ansible_os_family == "Darwin"
  package:
    name: mkcert
    state: "latest"

- name: copy in helpful binaries
  copy:
    src: "files/{{ item.src }}"
    dest: "~/.local/bin/{{ item.dest }}"
  with_items:
    - {src: "ssh-add-hippos", dest: "ssh-add-hippos"}
    - {src: "ssh-automed.bash", dest: "ssh-automed"}
    - {src: "alog.bash", dest: "alog"}

- name: ensure the repos directory exists
  file:
    path: "~/repos"
    state: "directory"

- name: clone automed
  git:
    repo: "git@gitlab.com:HealthTensor/automed.git"
    dest: "~/repos/automed"
    update: no

- name: setup symbolic link for automed-compose
  file:
    src: "~/repos/automed/bin/automed-compose.sh"
    dest: "~/.local/bin/htac"
    state: "link"
