---
- name: install automed dependencies
  become: yes
  package:
    name: "{{ item }}"
    state: latest
  with_items:
    - ansible
    - python-jinja
    - certbot

- name: install mkcert from aur
  become: yes
  command: "pikaur -Sy --noconfirm --noprogressbar mkcert"

- name: copy in helpful binaries
  copy:
    src: "files/{{ item }}"
    dest: "~/bin/{{ item }}"
  with_items:
    - "ssh-add-hippos"

- name: ensure the repos directory exists
  file:
    path: "~/repos"
    state: directory

- name: clone automed
  git:
    repo: "git@gitlab.com:HealthTensor/automed.git"
    dest: "~/repos/automed"
    update: no

- name: setup symbolic link
  file:
    src: "~/repos/automed/bin/automed-compose.sh"
    dest: "~/bin/ac"
    state: link

