---
- hosts: localhost
  connection: local
  remote_user: "{{ local_user }}"
  roles:
    - {role: git, tags: git}
    - {role: core, tags: core}
    - {role: dotsible, tags: dotsible}
    - {role: tmux, tags: tmux}
