---
- import_playbook: base.yml
  vars:
    sudo_group: "sudo"
    dotsible_playbook: "cli"

- hosts: localhost
  connection: local
  remote_user: "{{ local_user }}"
  roles:

    - role: ssh
      tags: ssh
      vars:
        ssh_package_name: ssh

    - role: emacs
      tags: emacs

    - role: claude
      tags: claude

    - role: opencode
      tags: opencode

    - role: gh
      tags: gh

    - role: gog
      tags: gog
