---
- import_playbook: base.yml
  vars:
    sudo_group: "sudo"

- hosts: localhost
  connection: local
  remote_user: "{{ local_user }}"
  roles:

    - role: ssh
      tags: ssh
      vars:
        ssh_package_name: ssh

    - role: emacs
      tags: emacs
      vars:
        emacs_mu4e_enabled: no
        emacs_org_jira_enabled: no
        emacs_org_page_enabled: no
        emacs_prodigy_enabled: no
