---
- hosts: localhost
  connection: local
  remote_user: "{{ local_user }}"
  roles:

    - {role: git, tags: git}

    - role: core
      tags: core
      vars:
        sudo_group: "sudo"

    - {role: bash, tags: bash}

    - {role: dotsible, tags: dotsible}

    - role: ssh
      tags: ssh
      vars:
        ssh_package_name: ssh

    - role: emacs
      tags: emacs
      vars:
        emacs_mu4e_enabled: no
        emacs_org_jira_enabled: no
        emacs_prodigy_enabled: no

    - {role: tmux, tags: tmux}
