---
- import_playbook: base.yml
  vars:
    dotsible_playbook: "lenovo-flex-4"

- hosts: localhost
  connection: local
  remote_user: "{{ local_user }}"
  roles:
    - role: arch
      tags: arch
      vars:
        wifi_interface: "wlp3s0"

    - {role: net-utils, tags: net-utils}
    - {role: mlocate, tags: mlocate}
    - {role: ssh, tags: ssh}
    - {role: bluetooth, tags: bluetooth}
    - {role: pulseaudio, tags: pulseaudio}
    - {role: python, tags: python}
    - {role: nodejs, tags: nodejs}
    - {role: ruby, tags: ruby}
    - {role: offlineimap, tags: offlineimap}
    - role: emacs
      tags: emacs
      vars:
        emacs_font_size: "15"
        emacs_powerline_scale: "1.0"
        emacs_themes: "spacemacs-light spacemacs"

    - {role: nextcloud, tags: nextcloud}
    - {role: xorg, tags: xorg}

    - role: stumpwm
      tags: stumpwm
      vars:
        dmenu_font_size: "12"
        device_scale_factor: "1.0"

    - role: clipster
      tags: clipster

    - role: dunst
      tags: dunst
      vars:
        dunst_font: "Terminus 12"

    - role: conky
      tags: conky

    - role: termite
      tags: termite
      vars:
        termite_font_size: "11"

    - {role: xapps, tags: xapps}
    - {role: xscreensaver, tags: xscreensaver}
    - {role: gitup, tags: gitup}
    - {role: backup, tags: backup}
    - {role: libvirt, tags: libvirt}
    - {role: docker, tags: docker}
    - {role: vpn, tags: vpn}

    - {role: automed, tags: automed}
    # - {role: pass, tags: pass}
