---
- hosts: localhost
  connection: local
  remote_user: "{{ local_user }}"
  roles:
    - {role: git, tags: git}
    - {role: core, tags: core}
    - {role: arch, tags: arch}
    - {role: fish, tags: fish}
    - {role: offlineimap, tags: offlineimap}
    - role: emacs
      tags: emacs
      vars:
        emacs_font_size: "17"
        emacs_powerline_scale: "1.0"
    - {role: tmux, tags: tmux}
    - {role: nextcloud, tags: nextcloud}
    - {role: xorg, tags: xorg}
    - role: stumpwm
      tags: stumpwm
      vars:
        dmenu_font_size: "12"
        device_scale_factor: "1.2"
    - role: tint2
      tags: tint2
      vars:
        tint2_font: "Cantarell Bold 12"
        tint2_font_small: "Cantarell Bold 10"
        tint2_systray_icon_size: "24"
        tint2_launcher_icon_size: "32"
        tint2_task_height: "40"
    - role: termite
      tags: termite
      vars:
        termite_font_size: "12"
    - {role: xapps, tags: xapps}
    - {role: xscreensaver, tags: xscreensaver}
    - {role: docker, tags: docker}
    - {role: automed, tags: automed}
    # - {role: pass, tags: pass}
