---
# This config assumes OS X on a 2022 MacBook Pro M1

- import_playbook: base.yml
  vars:
    dotsible_playbook: "osx"
    # Use homebrew's Python3
    ansible_python_interpreter: "/opt/homebrew/bin/python3"
    privileged_package_install: false

- hosts: localhost
  connection: local
  remote_user: "{{ local_user }}"
  vars:
    dotsible_playbook: "osx"
    ansible_python_interpreter: "/opt/homebrew/bin/python3"
    privileged_package_install: false
  roles:
    # - role: python
    #   tags: python

    - role: offlineimap
      tags: offlineimap

    - role: zsh
      tags: zsh

    - role: emacs
      tags: emacs

    - role: automed
      tags: automed

    - role: pass
      tags: pass
