---
# This config assumes Arch Linux on a System76 Thelio

- import_playbook: base.yml
  vars:
    dotsible_playbook: "sam"
    privileged_package_install: true

- hosts: localhost
  connection: local
  remote_user: "{{ local_user }}"
  roles:
    - role: arch
      tags: arch

    - role: ssh
      tags: ssh

    # TODO: hand off to guix
    # role: python
    #   tags: python

    # - role: nodejs
    #   tags: nodejs

    # - role: ruby
    #   tags: ruby

    - role: offlineimap
      tags: offlineimap

    # TODO: hand off to guix
    - role: emacs
      tags: emacs

    - role: nextcloud
      tags: nextcloud

    #- {role: backup, tags: backup}

    # {role: libvirt, tags: libvirt}

    # Do I need docker?
    - role: docker
      tags: docker

    #- {role: vpn, tags: vpn}
