---
- name: ensure fish and related packages are installed
  package:
    name: "{{ item }}"
    state: latest
  with_items:
    - fish
    - fzf

- name: create fish config dir
  file:
    name: "~/.config/fish/functions"
    state: directory

- name: copy in fish fzf config
  copy:
    src: "files/functions/fish_user_key_bindings.fish"
    dest: "~/.config/fish/functions/fish_user_key_bindings.fish"

- name: copy in fish_greeting
  copy:
    src: "files/functions/fish_greeting.fish"
    dest: "~/.config/fish/functions/fish_greeting.fish"

- name: copy in fish_prompt
  copy:
    src: "files/functions/fish_prompt.fish"
    dest: "~/.config/fish/functions/fish_prompt.fish"

- name: copy in fish vars
  copy:
    src: "files/fish_variables"
    dest: "~/.config/fish/fish_variables"

# - name: set initial global fish variables
#   command: fish "~/.config/fish/set_initial_globals.fish"
#   run_once: true

- name: configure jtmoulia to use fish
  become: true
  user:
    name: jtmoulia
    shell: /usr/bin/fish
