---

- name: install stumpwm-git
  command: pikaur -Sy --noconfirm --noprogressbar stumpwm-git

- name: install supporting packages
  become: yes
  package:
    name: "{{ item }}"
    state: latest
  with_items:
    - light
    - dmenu
    - clipmenu
    - tint2

- name: ensure .stumpwm.d directory exists
  file:
    path: "~/.stumpwm.d"
    state: directory

- name: template in the stumpwm init.lisp
  template:
    src: "templates/init.lisp.j2"
    dest: "~/.stumpwm.d/init.lisp"
  tags: [stumpwm-config]
