---

- name: install stumpwm-git
  command: pikaur -Sy --noconfirm --noprogressbar stumpwm-git

- name: install supporting packages
  become: yes
  package:
    name: "{{ item }}"
    state: latest
  with_items:
    # light adjusts the screen brightness
    - light
    # dmenu is a fuzzy finder
    - dmenu
    # clipmenu is a dmenu for the clipboard
    - clipmenu
    # tint2 is a task bar & dock
    - tint2
    # maim does screen grabs
    - maim

- name: ensure .stumpwm.d directory exists
  file:
    path: "~/.stumpwm.d"
    state: directory

- name: template in the stumpwm init.lisp
  template:
    src: "templates/init.lisp.j2"
    dest: "~/.stumpwm.d/init.lisp"
  tags: [stumpwm-config]
